<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form method="POST">
                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <input type="text" id="form3Example3" class="form-control form-control-lg" placeholder="Votre username" name="username"/>
                        <label class="form-label" for="form3Example3">Votre username</label>
                        <?php if(isset($_SESSION['wrongName'])) : ?>
                            <p style="color:red">Identifiant inconnu</p>
                        <?php unset($_SESSION['wrongName']) ?>
                        <?php endif; ?>
                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <input type="password" id="form3Example4" class="form-control form-control-lg" placeholder="Entrez votre mot de passe" name="password"/>
                        <label class="form-label" for="form3Example4">Votre mot de passe</label>
                        <?php if(isset($_SESSION['wrongPassword'])) : ?>
                            <p style="color:red">Mauvais mot de passe</p>
                        <?php unset($_SESSION['wrongPassword']) ?>
                        <?php endif; ?>
                    </div>

                    <div class="text-center text-lg-start mt-4 pt-2">
                        <button type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;">Connexion</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

    </div>
</section>